config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "user_index", to: "users#index"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  delete "logout", to: "sessions#destroy"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"


  get "/auth/twitter/callback", to: "omniuth_callbacks#twitter"
  

  # Defines the root path route ("/")
   root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "you must be signed in to do that." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    def index  
      
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController

    def twitter 
        render plain: "success"
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

    def new 
    end

    def create 
        @user = User.find_by(email: params[:email])

        if @user.present?
            PasswordMailer.with(user: @user).reset.deliver_now
        end
          redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password"
    end

    def edit 
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired. Pleas try again "
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "YOur password was reset successfully. Pleas sign in."
        else
            render :edit 
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

    before_action :require_user_logged_in!

    def edit 
    end

    def update 
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to sign_up_path, notice: "logged out"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new
    end

    def create 
         @user =User.new(user_params)
         @user.save 
         session[:user_id] = @user.id
         redirect_to root_path
    end
    def index 
        @user = User.all
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Logi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar"%>
      <div class="container">
        <%= render partial: "shared/flash"%>
          <%= yield %>
      </div>  
  </body>
</html>

app/views/main/index.html.erb
<div class= "d-flex align-item-center justify-content-center">
   <h1>Welcom </h1>
</div>

   

app/views/password_resets/edit.html.erb
<h1>Reset your password?</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form|%>
    <div class="form-group">
        <%=form.label :Password%>
        <%= form.password_field :password, class: 'form-control', placeholder: 'Enter Your Password'%>
    </div> 
    
    <div class="form-group">
        <%= form.label :Password_confirmation%>
        <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'Enter Your Password confirmation'%>
    </div><br>
    <div class="form-group">
        <%= form.submit "Reset Password", class: 'btn btn-primary'%>
    </div>

<%end%>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |form|%>
    <div class="form-group">
        <%=form.label :Email%>
        <%= form.text_field :email, class: 'form-control', placeholder: 'Enter Your Email'%>
    </div><br>
    <div class="form-group">
        <%= form.submit "Reset Password", class: 'btn btn-primary'%>
    </div>

<%end%>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
    <div class="alert alert-info mt-4" role="alert">
      <%= flash[:notice]%>
    </div>  
<%end%>    

<% if flash[:alert]%>
    <div class="alert alert-warning mt-4" role="alert">
      <%= flash[:alert]%>
    </div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="user_index">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/">Main</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <%if Current.user%>
         <li class="nav-item">
          <%= link_to Current.user.email, edit_password_path, class: "nav-link"%>
         </li> 
         <li class="nav-item">
          <%= button_to "logout", logout_path, method: :delete , class: "btn btn-outline-success me-2"%>
         </li> 
        <% else %>
         <li class="nav-item">
          <%= link_to 'Sign Up', sign_up_path, class: "nav-link"%>
         </li> 
         <li class="nav-item">
          <%= link_to 'Sign In', sign_in_path, class: "nav-link"%>
         </li> 
        <%end%> 
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<h1>Index</h1>
<%= @user.name%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row justify-content-center">
    <%= form_with model: @user, url: sign_up_path do |form|%>
        <div class="form-group">
          <%=form.label :Name%>
          <%= form.text_field :name, class: 'form-control', placeholder: 'Enter Your Name'%>
        </div>
        <div class="form-group">
          <%=form.label :Email%>
          <%= form.text_field :email, class: 'form-control', placeholder: 'Enter Your Email'%>
        </div>
        <div class="form-group">
          <%=form.label :Password%>
          <%= form.password_field :password, class: 'form-control', placeholder: 'Enter Your Password'%>
        </div> 
       
        <div class="form-group">
          <%= form.label :Password_confirmation%>
          <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'Enter Your Password confirmation'%>
        </div><br>
        <div class="form-group">
          <%= form.submit "Sign Up", class: 'btn btn-primary'%>
        </div>
    <%end%>
</div>    